### ISSUE TITLE
Subparticle box size 

### ISSUE THREAD

**Issue by prokhoroff** [scipion-em/scipion-em-localrec#27]
I’m trying to use Localized Reconstruction plugin in Scipion 3. I imported particles from Relion 3.1, defined subparticles, filtered them and extracted with a new box size. Everything worked seemingly okay. But when I try and do 2D or 3D classification or 3D auto-refine the subparticles are treated as if they have the size of the original imported particles - 972 px instead of 168 px. For instance, in 3D auto-refine I have "ERROR The reference box size is 168 A, but the box size of the first optics group of the data is 972 A!” (which is btw not correct as the reference box size is 168 px and the pixel size is 1.1 A) Particles in particles.mrcs have correct dimensions and the problem seems to be in metadata. I opened particles.sqlite from the extraction job and it looks like every particle has its own relion optics group header. I changed rlnImageSize from 972 to 168 in all entries but still have the same error from 3D auto-refine when I try using corrected particles.sqlite. What would be the better way to overcome this?

Thank you,

Nikolai

**Comment by JuhaHuiskonen** [comment]
I am having the same issue. rlnImageSize is the size of the original particle, not that of the sub-particle

**Comment by azazellochg** [comment]
I've just released beta5 of relion plugin. I have checked this and at least 2D classification is working for subparticles, the imagesize is correct. Please update your relion plugin

**Comment by azazellochg** [comment]
I didn't understand this part: " it looks like every particle has its own relion optics group header". Do you have more than 1 opticsgroup?

**Comment by JuhaHuiskonen** [comment]
@vabrishami has updated our Relion plugin to version beta5.  I have reran 'relion - reconstruct' and also 'relion - 2D classification'.  My subparticle size is 256.  Still the input_particles.star produced in both of these runs shows 1024 rlnImageSize (which is the size of my particle).  It seems these protocols still read the value of the particle, not the size of the subparticle.

**Comment by azazellochg** [comment]
Interesting. I have run the part of TestLocalizedRecons and added 2d cls at the end:
![image](https://user-images.githubusercontent.com/6952870/97110198-c4291480-16cf-11eb-8e24-f399aeefe567.png)
Are you able to reproduce my results? If yes, then something else must be wrong. 

Maybe you could create the workflow for me with say 10 particles that I can reproduce?

**Comment by JuhaHuiskonen** [comment]
I confirm that I can reproduce your results.  I did

scipion test --run localrec.tests.test_protocol_localized_reconstruction

and added 'relion - 2D clssification' to it.  The particle size is correct in the STAR file (26 pix in this test)

I keep exploring what is different in my 'real' workflow.  That starts with movies, picking is in Xmipp, particle extraction in relion.

**Comment by JuhaHuiskonen** [comment]
So it seems the culprit is 'relion - particles extraction' protocol.  If I use Xmipp instead, and then continue the same LocalRec workflow, the particle size is correctly set in subsequent Relion runs.

**Comment by azazellochg** [comment]
Thank, Juha. Could you export the workflow into json and attach here? I
assume you are using relion extr ptcls on particle since I tried on
subparticles and it doesnt work.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by JuhaHuiskonen** [comment]
First I used 'relion - particles extraction' to extract the normal particles. Relion runs on the particles extracted this way work fine, the issue is only with the size&optics group with the sub-particles later on.  However, when I use Xmipp to extract the particles from micrographs, then the LocalRec workflow part works. (Sub-particles are always extracted from particles using the LocalRec protocol.) So as long as the Particles are extracted with Xmipp and sub particles normally using LocalRec everything works.

**Comment by prokhoroff** [comment]
I did my localrec project in Scipion 3 to the point when I have subparticles extracted. Then, I opened it in Scipion 2 and the subparticle size was recognized correctly. I used relion class2d and relion reconstruct quite successfully so far. Surprising compatibility!

Yes. I have two opticsgroups in my dataset.

**Comment by azazellochg** [comment]
@JuhaHuiskonen I still don't see the whole picture. relion extract particles produces particles without alignments, so they cant be used in localrec - define subparticles. Do you assign alignments or run refinements?

**Comment by vabrishami** [comment]
@azazellochg we are talking about sub-particles extraction. So it comes after define sub-particles

**Comment by JuhaHuiskonen** [comment]
@azazellochg After relion extract particles (or now xmipp as it doesn't work with relion for me) I indeed use 'pwem alignment assign' before 'localrec - define subparticles'

**Comment by azazellochg** [comment]
Hooray, I was finally able to reproduce the wrong imageSize! I used this workflow. 
![image](https://user-images.githubusercontent.com/6952870/97438082-3ee66f80-191c-11eb-800e-2b5d133d2747.png)

**Comment by azazellochg** [comment]
So, the problem is with localrec-extraction. Since when using relion 3.1 you have opticsgroup and opticsgroupinfo in the acquisition dict (in this case associated with input particles for localrec extr), the protocol has to update them (this is done in relion extraction protocol), so that the optics table will be generated correctly during convertinputStep of any relion protocol (2d, 3d etc.) @delarosatrevin am I right?

**Comment by delarosatrevin** [comment]
Yes, that is the issue. I was discussing it with @JuhaHuiskonen about it. A bigger issue is that it is not only localrec-extraction but any protocol that modifies size (e.g xmipp-extract, preprocess, etc). So, maybe we need to review the convert in Relion and use the existing opticsTable, but update "higher priority" properties in input sets, e.g particle size/pixel size. In this way, other protocols do not need to worry about opticsGroups or not, that is a Relion property...and we could still preserve its propagation.

**Comment by azazellochg** [comment]
Hi all,
I'd appreciate if you could pull the latest devel branch and try to see if the issue is fixed.

**Comment by JuhaHuiskonen** [comment]
Hi @azazellochg. I have updated.  Now different downstream protocols that can change the box or pixel size or both ('localrec - extract subparticles', 'xmipp3 - crop/resize particles'  and 'relion - particles extraction') don't seem to cause this issue anymore. When I run a relion protocol which such particles, the box size and pixel size are correctly set in the optics table. Thanks!

**Comment by delarosatrevin** [comment]
Thanks @JuhaHuiskonen and @azazellochg !
