### ISSUE TITLE
plugin code is outdated

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-localrec#3]
I have no idea where this code came from, but it does not have latest changes as in scipion 1.2.1. Example: https://github.com/I2PC/scipion/commit/c1e8bf5ef4a2cdd159b2a05e23136c998ce3048d
This code is missing in the plugin..

**Comment by azazellochg** [comment]
Ah, apparently the history was not preserved when creating this plugin..

**Comment by rmarabini** [comment]
Hi @azazellochg,
 
    I am reviewing this package. I see that the code in this plugin is different from what we had in scipion 1.2.1 but is there anything missing?. I understand that relion is not longer used to compute the symmetry matrices therefore, I2PC/scipion@c1e8bf5 may be not longer needed.

**Comment by azazellochg** [comment]
Hi @rmarabini I'll reply in half a year :) You can close this, I have no desire to check whether this is relevant or not anymore.

**Comment by delarosatrevin** [comment]
@rmarabini Please be in contact with @vabrishami and @JuhaHuiskonen , that are the developers and maintainers of this plugin.

**Comment by rmarabini** [comment]
Hi @delarosatrevin,

   I already contacted the official developers of localrec because I want to add a extra option to the package, Independently, I show this issue and I wanted to know if this have been solved or not.

**Comment by rmarabini** [comment]
I close this issue since it is unclear if the problem persists.
