### ISSUE TITLE
ProtLocalizedExtraction

### ISSUE THREAD

**Issue by vsreddyHI** [scipion-em/scipion-em-localrec#41]
I am using Scipion v3.0.12 Eugenius-3..0.27 (core)
pyworkflow: 3.0.27
plugin: localrec
plugin v3.0.3

*** LocalRec plugin hangs while extracting the subvolumes/particles (see attached screenshot)

According to Juha Huiskonen, the same work well in 
pyworkflow: 3.0.5
plugin: localrec
plugin v: 3.0.1

![scipion_error](https://user-images.githubusercontent.com/122119292/211079630-1586538e-77fe-4a32-a226-e15b3802fe2d.png)

**Comment by rmarabini** [comment]
Hi @JuhaHuiskonen and @vsreddyHI ,

    @vsreddyHI,  each protocol comes with a collection of tests. Can you execute the command

scipion3 tests --grep localrec --run

this command will execute all test related with localrec. If all test are successful  then there is something unexpected in your data set, otherwise we have introduced a bug in the last release. 

I just run the test locally with:
scipion3 version
Scipion v3.0.12 - Eugenius
pyworkflow - 3.0.27
pwem - 3.0.23
scipion-em-localrec        3.0.3    

and the results look OK.

**Comment by pconesa** [comment]
Hi, I can confirm that the tests also worked fine for me:
00004:   Hostname: youyou
00005:   PID: 93597
00006:   pyworkflow: 3.0.27
00007:   plugin: localrec
00008:   plugin v: 3.0.3
00009:   currentDir: /home/pablo/ScipionUserData/projects/TestLocalizedRecons
00010:   workingDir: Runs/000540_ProtLocalizedExtraction
00011:   runMode: Continue
00012:             MPI: 1
00013:         threads: 1
00014:    Starting at step: 1
00015:    Running steps 
00016:   STARTED: createOutputStep, step 1, time 2023-01-09 12:27:16.512499
00017:   
00018:     0/120 (  0%) 120 to go
00019:     1/120 (  0%) 119 to go
00020:   101/120 ( 84%)  19 to go
00021:   120/120 (100%)   0 to go
00022:   FINISHED: createOutputStep, step 1, time 2023-01-09 12:27:17.242329
00023:   *** Last status is finished 
00024:   Cleaning temp folder....
00025:   ------------------- PROTOCOL FINISHED

I'd say, going back to other versions will probably not fix it.

Do you @vsreddyHI , see anything in the error log tab?

**Comment by JuhaHuiskonen** [comment]
This issue was most likely unrelated to localrec plugin / scipion
