### ISSUE TITLE
request for three new features

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-localrec#7]
1) In most cases I am interested in processing viruses and extracting sub-volumes centered in the 5-fold axis (pentons) so I would like to add an extra possibility in localized subparticles so if the symmetry selected is ixxx (icosahedral) you can select in adition to "cmm file" and "string" also the option "vertex"

2) I will also like to rewrite the way the symmetry is provided, now we type a "string" for example "i2". My suggestion is to provide a list as done, for example, in "extract_unit_cell" (xmipp package). (This is an aesthetic change)

3) In the protocol filter_subunit I would like to add another option. This option will allow to discard particles that are at a distance smaller than a threshold from the center. That is, I only want to keep the subparticles in the periphery of my virus.

**Comment by vabrishami** [comment]
1. We will consider it for the future versions of the package since we should generalize it.
2. It is done.
3. Actually, this feature is similar to our "side view" option if filter subunits.
