### ISSUE TITLE
from one user here at cnb, betatesting scipion 2.0

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-localrec#9]
he is getting this errors:

00076:   ERROR:
00077:   MlOptimiser::readStar: File Runs/003954_ProtRelionRefine3D/extra/relion_it020_optimiser.star cannot be read.
00078:   --------------------------------------------------------------------------
00079:   MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
00080:   with errorcode 1.
00081:
00082:   NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
00083:   You may or may not see output from other processes, depending on
00084:   exactly when Open MPI kills them.
00085:   --------------------------------------------------------------------------
00086:   [vesta:48932] 2 more processes have sent help message help-mpi-api.txt / mpi-abort
00087:   [vesta:48932] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
00088:   Traceback (most recent call last):
00089:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00090:       self._run()
00091:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00092:       resultFiles = self._runFunc()
00093:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00094:       return self._func(*self._args)
00095:     File "/usr/local/scipion/software/lib/python2.7/site-packages/relion/protocols/protocol_multibody.py", line 235, in multibodyRefineStep
00096:       self._runProgram('relion_refine', args)
00097:     File "/usr/local/scipion/software/lib/python2.7/site-packages/relion/protocols/protocol_multibody.py", line 232, in _runProgram
00098:       self.runJob(prog, params)
00099:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 1321, in runJob
00100:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00101:     File "/usr/local/scipion/pyworkflow/protocol/executor.py", line 70, in runJob
00102:       env=env, cwd=cwd, gpuList=self.getGpuList())
00103:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 52, in runJob
00104:       return runCommand(command, env, cwd)
00105:     File "/usr/local/scipion/pyworkflow/utils/process.py", line 67, in runCommand
00106:       env=env, cwd=cwd)
00107:     File "/usr/local/scipion/software/lib/python2.7/subprocess.py", line 190, in check_call
00108:       raise CalledProcessError(retcode, cmd)
00109:   CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --healpix_order 4 --gpu 0:2 --pool 3 --oversampling 1 --auto_local_healpix_order 4 --o Runs/004681_ProtRelionMultiBody/extra/run --dont_combine_weights_via_disc  --offset_range 3.0 --solvent_correct_fsc  --reconstruct_subtracted_bodies  --continue Runs/003954_ProtRelionRefine3D/extra/relion_it020_optimiser.star --multibody_masks Runs/004681_ProtRelionMultiBody/extra/input_body.star --offset_step 0.75' returned non-zero exit status 1
00110:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --healpix_order 4 --gpu 0:2 --pool 3 --oversampling 1 --auto_local_healpix_order 4 --o Runs/004681_ProtRelionMultiBody/extra/run --dont_combine_weights_via_disc  --offset_range 3.0 --solvent_correct_fsc  --reconstruct_subtracted_bodies  --continue Runs/003954_ProtRelionRefine3D/extra/relion_it020_optimiser.star --multibody_masks Runs/004681_ProtRelionMultiBody/extra/input_body.star --offset_step 0.75' returned non-zero exit status 1
00111:   FAILED: multibodyRefineStep, step 2
00112:     2019-05-07 14:43:51.163872
00113:   *** Last status is failed
00114:   ------------------- PROTOCOL FAILED (DONE 2/4)

and from localrec-localized subparticles:

00022:   Traceback (most recent call last):
00023:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00024:       self._run()
00025:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00026:       resultFiles = self._runFunc()
00027:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00028:       return self._func(*self._args)
00029:     File "/usr/local/scipion/software/lib/python2.7/site-packages/localrec/protocols/protocol_localized.py", line 155, in createOutputStep
00030:       self.alignSubparticles)
00031:     File "/usr/local/scipion/software/lib/python2.7/site-packages/localrec/utils.py", line 380, in create_subparticles
00032:       ctf.setDefocusU(subpart.getDefocusU() + z)
00033:   AttributeError: 'Particle' object has no attribute 'getDefocusU'
00034:   Protocol failed: 'Particle' object has no attribute 'getDefocusU'
00035:   FAILED: createOutputStep, step 1
00036:     2019-04-11 18:58:48.605257
00037:   *** Last status is failed
00038:   ------------------- PROTOCOL FAILED (DONE 1/1)

**Comment by rmarabini** [comment]
Hi @pconesa ,

   Last version of localrec does not use relion any longer. Therefor,e I think the fix for this problem is to use scipion 2.0 and update the plugin.

**Comment by pconesa** [comment]
Is the update available in pypi?

**Comment by rmarabini** [comment]
yes
